### PR TITLE
Updated readme with extra guff

### PR DESCRIPTION
**Pull request by amleaver**
Please take a look at this!

---
This change is [Reviewable](https://reviewable.io/reviews/amleaver/hairy-slackbot/2)

### CODE REVIEW

**Comment by andrew-david-smith** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 2 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2#-KtMytRZZTi7HZCysvkJ:-KtMytRZZTi7HZCysvkK:b45bbu4) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/5b415fc5613a3d5ba07dc2fccd989343f09869a9/README.md#L2)):*
> ```Markdown
> # hairy-slackbot
> Like slackbot, but hairier
> ```

This looks terrible

---

*[README.md, line 2 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2#-KtMyxx6SpUq7oS_r1IW:-KtMyxx6SpUq7oS_r1IX:bhtsq31) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/5c28f67024eb1d72a9e82fd70ed5e251dc6e9c43/README.md#L2)):*
> ```Markdown
> # hairy-slackbot
> Like slackbot, but hairier and betterer
> ```

But I do like this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2)*

**Comment by andrew-david-smith** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2)*

**Comment by amleaver** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 2 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2#-KtMytRZZTi7HZCysvkJ:-KtMzRcgvHSCUbmvHMi0:bjiv1xt) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/5b415fc5613a3d5ba07dc2fccd989343f09869a9/README.md#L2)):*
<details><summary><i>Previously, Thranriel (Andrew Smith) wrote…</i></summary><blockquote>

This looks terrible
</blockquote></details>

Yeah, that's the old change and I'm not going to update it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2)*

**Comment by andrew-david-smith** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 2 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2#-KtMytRZZTi7HZCysvkJ:-KtMzurt7A_zRc-pHd5-:bb6vskf) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/5b415fc5613a3d5ba07dc2fccd989343f09869a9/README.md#L2)):*
<details><summary><i>Previously, amleaver (Alex Leaver) wrote…</i></summary><blockquote>

Yeah, that's the old change and I'm not going to update it
</blockquote></details>

Fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2)*

**Comment by andrew-david-smith** [comment]
*[a discussion](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2#-KtN-qer5K_plErsCNDb:-KtN-qesBgTkI0s6j_eE:btykb1w) (no related file):*
Hello!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/2)*

**Pull request merged**
