### PR TITLE
Added the hairy file

### PR DESCRIPTION
**Pull request by andrew-david-smith**
The hairy file, so that the hairy fairy knows what to do

---
This change is [Reviewable](https://reviewable.io/reviews/amleaver/hairy-slackbot/1)

### CODE REVIEW

**Comment by amleaver** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[hairy.file, line 1 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1#-KtMuLeKQ6e6TIUtnylD:-KtMuLeLBA_qS-zofK4E:b-umsk3c) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/e39a19016b4cdc11a297260d75adbf5499812025/hairy.file#L1)):*
> ```
> It's Hairy!
> ```

It's not hairy enough. We need this file to be sup hairy or what's the point in this project?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1)*

**Comment by andrew-david-smith** [comment]
*[hairy.file, line 1 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1#-KtMuLeKQ6e6TIUtnylD:-KtMuwFU93nerJ93nw-Y:b5981tt) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/e39a19016b4cdc11a297260d75adbf5499812025/hairy.file#L1)):*
<details><summary><i>Previously, amleaver (Alex Leaver) wrote…</i></summary><blockquote>

It's not hairy enough. We need this file to be sup hairy or what's the point in this project?
</blockquote></details>

What does "sup" mean. I am not "down with the kids" I am afraid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1)*

**Comment by amleaver** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[hairy.file, line 1 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1#-KtMuLeKQ6e6TIUtnylD:-KtMvd1683111t-g_gMT:b-konjky) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/e39a19016b4cdc11a297260d75adbf5499812025/hairy.file#L1)):*
<details><summary><i>Previously, Thranriel (Andrew Smith) wrote…</i></summary><blockquote>

What does "sup" mean. I am not "down with the kids" I am afraid.
</blockquote></details>

It's short for super. We need to target the youth demographic so I'm incorporating their 'ling' (lingo) into this project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1)*

**Comment by amleaver** [comment]
This isn't good enough, see comments!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1#-:-KtMw4AQSTMECZCNus8c:bpqvxk5)*

**Comment by andrew-david-smith** [comment]
*[hairy.file, line 1 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1#-KtMuLeKQ6e6TIUtnylD:-KtMwraEXwj2JhEponOe:b-m0g8od) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/e39a19016b4cdc11a297260d75adbf5499812025/hairy.file#L1)):*
<details><summary><i>Previously, amleaver (Alex Leaver) wrote…</i></summary><blockquote>

It's short for super. We need to target the youth demographic so I'm incorporating their 'ling' (lingo) into this project.
</blockquote></details>

what about now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1)*

**Comment by amleaver** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[hairy.file, line 1 at r1](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1#-KtMuLeKQ6e6TIUtnylD:-KtMx7WgryDP-KPwt6FJ:bb71kmx) ([raw file](https://github.com/amleaver/hairy-slackbot/blob/e39a19016b4cdc11a297260d75adbf5499812025/hairy.file#L1)):*
<details><summary><i>Previously, Thranriel (Andrew Smith) wrote…</i></summary><blockquote>

what about now?
</blockquote></details>

Okay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amleaver/hairy-slackbot/1)*

**Pull request merged**
